### ISSUE TITLE
Support for Sub-Documents

### ISSUE THREAD

**Issue by adamdickinson** [timhall/rollup-plugin-graphql-tag#4]
Hoping to enable this to work for sub-documents too as it would allow us to make proper use of this plugin. Comments in the code indicate this as a TODO, so it looks to be on the cards.

And just to get the ball rolling: https://github.com/timhall/rollup-plugin-graphql-tag/pull/3

Btw, this is a super helpful plugin (a little surprised rollup doesn't support this kind of thing more comprehensively tbh)!

**Comment by timhall** [comment]
Closed by #3
